# Generated by Django 3.2 on 2021-09-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[[1, 'Normal'], [2, 'Administrativo']], null=True),
        ),
    ]
