# Generated by Django 3.2 on 2021-11-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_login_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[['normal', 'Normal'], ['administrativo', 'Administrativo']], default='normal', null=True),
        ),
    ]
