# Generated by Django 3.2 on 2021-11-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_login_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[('adm', 'Feminino'), ('normal', 'Masculino'), ('N', 'Nenhuma das opções')], default='normal', null=True),
        ),
    ]
